import type { FormState } from './types';

export const initialState: FormState = {
  propertyDetails: {
    address: '',
    city: '',
    state: '',
    zipCode: '',
    county: '',
    listingType: 'sale',
    priceDisplay: 'show',
    price: undefined,
    condition: '',
    conditionOther: '',
    specialEnhancements: '',
    deficiencies: '',
    bedrooms: undefined,
    bathrooms: undefined,
    squareFootage: undefined,
    emphasis: []
  },
  lotLocationDetails: {
    neighborhood: '',
    lotSize: '',
    nearbyAttractions: '',
    topography: '',
    view: 'None',
    viewOther: '',
    hasHOA: false,
    hoaFee: undefined,
    hoaFeeFrequency: 'monthly',
    lastYearTaxes: undefined,
    emphasis: []
  },
  houseDetails: {
    propertyType: '',
    propertyTypeOther: '',
    architecturalStyle: '',
    architecturalStyleOther: '',
    yearBuilt: undefined,
    levels: undefined,
    garageSpaces: undefined,
    carportSpaces: undefined,
    foundation: '',
    foundationOther: '',
    basementType: [],
    basementTypeOther: '',
    fenceType: '',
    fenceTypeOther: '',
    hasInGroundPool: false,
    hasAboveGroundPool: false,
    hasPorch: false,
    hasDeck: false,
    hasPatio: false,
    isHandicapAccessible: false,
    isFurnished: false,
    additionalStructures: [],
    additionalStructuresOther: '',
    emphasis: []
  },
  communityDetails: {
    amenities: [],
    amenitiesOther: '',
    poaName: '',
    schoolDistrict: '',
    emphasis: []
  },
  saleDetails: {
    isOwnerFinance: false,
    isLeaseOption: false,
    isForeclosure: false,
    isShortSale: false,
    isTenantOccupied: false,
    ownerFinanceTerms: '',
    leaseOptionTerms: '',
    emphasis: []
  },
  sellerDetails: {
    includeSeller: false,
    agentName: '',
    agency: '',
    website: '',
    phone: '',
    textNumber: '',
    facebookId: '',
    email: '',
    preferredContact: 'phone'
  },
  tone: 'General Audience',
  outputType: 'Website',
  includeCallToAction: false,
  inSpanish: false,
  mlsCharacterLimit: 750
};